{
    "openapi": "3.0.3",
    "info": {
        "title": "Yoint Payments - Subscriptions",
        "description": "API gesti\u00f3n de pagos recurrentes Yoint.",
        "termsOfService": "https://yoint.co/terminos-y-condiciones/",
        "contact": {
            "email": "sales@yoint.co"
        },
        "version": "17"
    },
    "servers": [
        {
            "description": "SwaggerHub API Auto Mocking",
            "url": "https://virtserver.swaggerhub.com/SANTIAGOSALAS/Yoint_Payments/17"
        },
        {
            "description": "SwaggerHub API Auto Mocking",
            "url": "https://virtserver.swaggerhub.com/Yoint_Payments/9"
        },
        {
            "description": "development",
            "url": "https://9mx05d1mpj.execute-api.us-east-1.amazonaws.com/develop"
        }
    ],
    "paths": {
        "/api/payments/v1/create-subscription": {
            "post": {
                "tags": [
                    "Create subscriptions or non-recurring payments"
                ],
                "operationId": "createSubscription",
                "summary": "Crear suscripci\u00f3n debito o tarjetas con CVV, es importante especificar un \u00fanico m\u00e9todo de pago si es d\u00e9bito, se debe asegurar de que el campo correspondiente al objeto bankAccount est\u00e9 completo junto con el n\u00famero de cuenta. Si es pago con tarjeta, se debe incluir el objeto creditCard y excluir el objeto bankAccount.",
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Payment"
                            },
                            "example": {
                                "amount": 125741,
                                "payerAuthorization": true,
                                "subscription": {
                                    "starts": "2024-07-04T00:00:00+05:00",
                                    "ends": "2025-07-05T00:00:00+05:00",
                                    "runInterval": 1,
                                    "intervalUnit": "MONTHLY",
                                    "chargeDescription": "Compra comercio ABC",
                                    "retryOnFail": true,
                                    "maxRetries": 1,
                                    "retryInterval": 1,
                                    "retryIntervalUnit": "MONTHLY"
                                },
                                "payer": {
                                    "identityDocument": {
                                        "type": "CC",
                                        "number": "80154278"
                                    },
                                    "payerFullName": "pedro perez",
                                    "phoneNumber": "300789654",
                                    "email": "user@example.com",
                                    "bankAccount": {
                                        "type": "SAVINGS",
                                        "number": null,
                                        "financialEntity": {
                                            "id": "1013"
                                        }
                                    },
                                    "creditCard": {
                                        "pan": "41123456789012345",
                                        "cvc": "1234",
                                        "yyy": 2027,
                                        "mm": 12,
                                        "ownerName": "John Doe"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/SubscriptionCreationResponse"
                                }
                            }
                        }
                    },
                    "200": {
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Operaci\u00f3n exitosa"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/payments/v1/create-payment": {
            "post": {
                "tags": [
                    "Create subscriptions or non-recurring payments"
                ],
                "operationId": "createPayment",
                "summary": "Crea un pago unico, no es recurrente, billeteras o cuentas debito se debe informar Id de la entidad, tarjetas debito o credito, es importante especificar un \u00fanico m\u00e9todo de pago si es d\u00e9bito, se debe asegurar de que el campo correspondiente al objeto bankAccount est\u00e9 completo junto con el n\u00famero de cuenta. Si es pago con tarjeta, se debe incluir el objeto creditCard.",
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/OneShotPayment"
                            },
                            "example": {
                                "amount": 125741,
                                "payerAuthorization": true,
                                "paymentDate": "2024-07-04T00:00:00+05:00",
                                "chargeDescription": "Compra comercio ABC",
                                "iva": 19,
                                "payer": {
                                    "identityDocument": {
                                        "type": "CC",
                                        "number": "80154278"
                                    },
                                    "payerFullName": "John Doe",
                                    "phoneNumber": "300789654",
                                    "email": "user@example.com",
                                    "bankAccount": {
                                        "type": "SAVINGS",
                                        "number": null,
                                        "financialEntity": {
                                            "id": "0013"
                                        }
                                    },
                                    "creditCard": {
                                        "pan": "41123456789012345",
                                        "cvc": "1234",
                                        "yyy": 2027,
                                        "mm": 12,
                                        "ownerName": "John Doe"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PaymentCreationResponse"
                                }
                            }
                        }
                    },
                    "200": {
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Operaci\u00f3n exitosa"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/payments/v1/payment-link": {
            "post": {
                "tags": [
                    "Create subscriptions or non-recurring payments"
                ],
                "operationId": "createPaymentLink",
                "summary": "Genera un enlace de pago \u00fanico asociado a un orderID. Este pago no es recurrente y puede realizarse a trav\u00e9s de billeteras electr\u00f3nicas o cuentas de d\u00e9bito. No es obligatorio especificar el medio de pago al momento de crear el enlace.",
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/OneShotPayment"
                            },
                            "example": {
                                "currencyCode": "COP",
                                "amount": 125741,
                                "chargeDescription": "Compra comercio ABC",
                                "payer": {
                                    "identityDocument": {
                                        "type": "CC",
                                        "number": "80154278"
                                    },
                                    "payerFullName": "John Doe",
                                    "phoneNumber": "300789654",
                                    "email": "user@example.com"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PaymentCreationlinkResponse"
                                }
                            }
                        }
                    },
                    "200": {
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Operaci\u00f3n exitosa"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/payments/v1/{order-id}": {
            "get": {
                "tags": [
                    "Create subscriptions or non-recurring payments"
                ],
                "summary": "Obtiene los detalles de un pago, que puede ser una suscripci\u00f3n o un pago no recurrente.",
                "operationId": "getOrderDetails",
                "parameters": [
                    {
                        "name": "order-id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "description": "ID del pago a obtener"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Informaci\u00f3n del pago obtenida correctamente.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "subscription": {
                                            "$ref": "#/components/schemas/Subscription"
                                        },
                                        "paymentDetails": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/PaymentDetail"
                                            }
                                        },
                                        "payer": {
                                            "$ref": "#/components/schemas/Payer"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Solicitud incorrecta o par\u00e1metros inv\u00e1lidos"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Subscription": {
                "type": "object",
                "properties": {
                    "orderId": {
                        "type": "string",
                        "example": "aba1621d-4fd5-4d4b-b56e-2d294814d103"
                    },
                    "starts": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-11-03T00:00:00Z"
                    },
                    "ends": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-12-03T00:00:00Z"
                    },
                    "amount": {
                        "type": "number",
                        "format": "double",
                        "example": 2222
                    },
                    "runInterval": {
                        "type": "integer",
                        "example": 1
                    },
                    "intervalUnit": {
                        "type": "string",
                        "example": "DAILY"
                    },
                    "nextRun": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-11-04T00:00:00Z"
                    },
                    "chargeDescription": {
                        "type": "string",
                        "example": "Compra comercio ABC"
                    },
                    "retryOnFail": {
                        "type": "boolean",
                        "example": true
                    },
                    "maxRetries": {
                        "type": "integer",
                        "example": 1
                    },
                    "retryInterval": {
                        "type": "integer",
                        "example": 1
                    },
                    "retryIntervalUnit": {
                        "type": "string",
                        "example": "DAILY"
                    }
                }
            },
            "PaymentDetail": {
                "type": "object",
                "properties": {
                    "paymentDate": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-09-04T21:50:55.947Z"
                    },
                    "productType": {
                        "type": "string",
                        "example": "BBVA COLOMBIA"
                    },
                    "lastProductNumbers": {
                        "type": "string",
                        "example": "7745"
                    },
                    "status": {
                        "type": "string",
                        "example": "FAILED"
                    }
                }
            },
            "Payer": {
                "type": "object",
                "properties": {
                    "paymentInfo": {
                        "type": "object",
                        "properties": {
                            "payerFullName": {
                                "type": "string",
                                "example": "John Doe"
                            },
                            "identityDocument": {
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "example": "CC"
                                    },
                                    "number": {
                                        "type": "string",
                                        "example": "80154278"
                                    }
                                }
                            },
                            "bankAccount": {
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "example": "SAVINGS"
                                    },
                                    "number": {
                                        "type": "string",
                                        "nullable": true,
                                        "example": "100124587745"
                                    },
                                    "financialEntity": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string",
                                                "example": "1013"
                                            }
                                        }
                                    }
                                }
                            },
                            "creditCard": {
                                "type": "object",
                                "nullable": true,
                                "properties": {
                                    "pan": {
                                        "type": "string",
                                        "example": "XXXXXXXXXXXX2345"
                                    }
                                }
                            }
                        }
                    }
                },
                "description": "Solo se permite tarjeta o n\u00famero de cuenta, no ambas",
                "required": [
                    "identityDocument",
                    "bankAccount"
                ]
            },
            "Payment": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "number",
                        "format": "double",
                        "example": 125741
                    },
                    "subscription": {
                        "$ref": "#/components/schemas/Subscription"
                    },
                    "payer": {
                        "$ref": "#/components/schemas/Payer"
                    }
                }
            },
            "SubscriptionCreationResponse": {
                "type": "object",
                "properties": {
                    "orderId": {
                        "type": "string",
                        "example": "a44c7c2f-d664-4ee3-a544-6ff5b2ab8c71"
                    }
                }
            },
            "PaymentCreationResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number",
                        "example": 1
                    }
                }
            },
            "WebHookGet": {
                "type": "object",
                "properties": {
                    "ID": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "key": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "string"
                                }
                            }
                        },
                        "example": [
                            {
                                "id": "1",
                                "value": "exampleUrlNotification"
                            },
                            {
                                "id": "2",
                                "value": "exampleUrlnotification"
                            }
                        ]
                    }
                }
            },
            "PaymentCreationlinkResponse": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "example": "http://prueba.com?clientName=client?orderId=872458476252"
                    }
                }
            },
            "OneShotPayment": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "number",
                        "format": "double",
                        "example": 125741
                    },
                    "paymentDate": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-07-04T00:00:00+05:00"
                    },
                    "chargeDescription": {
                        "type": "string",
                        "example": "Compra comercio ABC"
                    },
                    "iva": {
                        "type": "number",
                        "format": "double",
                        "example": 19
                    },
                    "payer": {
                        "$ref": "#/components/schemas/Payer"
                    }
                }
            },
            "VerifyAccountRequest": {
                "type": "object",
                "properties": {
                    "identityDocument": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": "string",
                                "example": "CC"
                            },
                            "number": {
                                "type": "string",
                                "example": "80154278"
                            }
                        }
                    },
                    "bankAccount": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": "string",
                                "example": "SAVINGS"
                            },
                            "number": {
                                "type": "string",
                                "example": "100124587745"
                            },
                            "financialEntity": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer",
                                        "example": 1013
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "clientCredentials": {
                        "tokenUrl": "https://payments-dev.auth.us-east-1.amazoncognito.com/oauth2/token",
                        "scopes": {
                            "read": "leer",
                            "write": "escribir"
                        }
                    }
                }
            }
        }
    }
}